#!/usr/bin/env ruby
require "json"
require "net/http"
require "uri"

$tests = $errors = 0

def test(actual, expected)
  $tests += 1
  if actual != expected
    $errors += 1
    puts("at=error actual=#{actual} expected=#{expected}")
  end
end

puts("at=clean-database")
puts(`psql metrics -c 'delete from metrics'`)

if ENV["LOGPLEX_URL"].nil?
  puts("Must set LOGPLEX_URL.")
  exit
end

NUM_VALS = 50

t = Time.now
# Make sure we have enough time to work with the same bucket.
t = Time.now until t.sec < 55
bucket = (t.to_i * 60) / 60

puts("test=receive-logs")
NUM_VALS.times do
  `echo 'measure="l2met-simple-test"' | log-shuttle -batch-size=1`
end

puts("at=sleeping msg=\"Waiting for l2met to flush all data to storage\"")
sleep(1)

uri = URI.parse(ENV["L2MET_URL"] + "/buckets?limit=1")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Get.new(uri.request_uri)
request.basic_auth(uri.user, uri.password)
response = http.request(request)
buckets = JSON.parse(response.body)

test(buckets[0]["vals"].length, NUM_VALS)

print("\n\t Tests finished. tests=#{$tests} errors=#{$errors}\n")
