source :rubygems

gem 'mongrel', '1.2.0.pre2'
gem 'sinatra'
gem 'rack-ssl-enforcer'
gem 'rack-cors'
gem 'yajl-ruby'
gem 'atomic'
gem 'librato-metrics'
gem 'redis'
gem 'pg'
gem 'sequel'
gem 'aws-sdk'
gem 'scrolls', git: 'https://github.com/asenchi/scrolls.git'
gem 'sinatra-google-auth'
gem 'lock-smith', '0.0.8'
gem 'turn'
gem 'minitest'
